---
title: "CSE 3056 J Component"
author: 
       - "Lakshmi Sairam Kakarla"
       - "K Uday"
       - "M Nivas"
output: html_notebook
---

## Loaading required packages
```{r}
rm(list=ls())
library(ggplot2)
library(dplyr)
```

# data Preprocessing
## Loading the dataset
```{r}
online_data<-read.csv("online_shoppers_intention.csv")
head(online_data)
```

```{r}
str(online_data)
```

Checking for missing data
```{r}
sum(is.na(online_data))
```

The data set has no missing information. 
Weekend and Revenue are to be converted into factors.
Operating System, Browser,Region,Traffic Type also needs to be converted into factors
```{r}
online_data$Revenue<-as.factor(as.numeric(online_data$Revenue))
online_data$Weekend<-as.factor(as.numeric(online_data$Weekend))

online_data$OperatingSystems<-as.factor(online_data$OperatingSystems)
online_data$Browser<-as.factor(online_data$Browser)
online_data$Region<-as.factor(online_data$Region)
online_data$TrafficType<-as.factor(online_data$TrafficType)
```

```{r}
summary(online_data)
```

```{r}
library(dplyr)
library(formattable)
g <- online_data %>%
  group_by(Month) %>%
  summarise(BounceRates = n()) %>%
  mutate(Percentage = round(BounceRates / sum(BounceRates),3)) %>%
  arrange(desc(Percentage))
g$Percentage <- formattable::percent(g$Percentage)  
g
```

```{r}
library(ggplot2)
x <- online_data %>%
  group_by(Month) %>%
  summarise(ExitRates = n()) %>%
  mutate(Percente = round(ExitRates / sum(ExitRates),3)) %>%
  arrange(desc(Percente))
x$Percente <- formattable::percent(x$Percente)  
x
q<-ggplot(g, aes(x=reorder(Month, -Percentage),y=Percentage,fill=Month))+
  geom_bar(stat="identity")+theme_minimal()+
  ggtitle("Month wise bounce rates")
p<-ggplot(x, aes(x=reorder(Month, -Percente), y=Percente, fill=Month)) +
  geom_bar(stat="identity")+theme_minimal()+
  ggtitle("Month wise exit rates")
library(cowplot)
plot_grid(q, p,labels = "AUTO", ncol = 1)
```

```{r}
dupdata <- data.frame(online_data$Administrative_Duration,online_data$Informational_Duration,online_data$ProductRelated_Duration,online_data$Revenue)
pairs(dupdata)
```

```{r}
library(ggplot2)
p1<-ggplot(online_data, aes(x=Revenue, y=BounceRates, fill=Revenue)) +
  geom_boxplot() +
  ggtitle('Revenue on bouncerates')
p2<-ggplot(online_data, aes(x=Revenue, y=PageValues, fill=Revenue)) +
  geom_boxplot() +
  ggtitle('Revenue on pagevalues')
p3<-ggplot(online_data, aes(x=Revenue, y=ExitRates,fill=Revenue)) +
  geom_boxplot()+
  ggtitle('Revenue on exitrates')
library(cowplot)
plot_grid(p1, p2, p3,labels = "AUTO", ncol = 2)
```


```{r}
library("ggplot2")
a<-ggplot(online_data, aes(x=factor(Region)))+
 geom_bar(stat="count")+
 ggtitle('Region wise count')
b<-ggplot(online_data, aes(x=factor(TrafficType)))+
 geom_bar(stat="count")+
 ggtitle('Traffic wise count')
c<-ggplot(online_data, aes(x=factor(Browser)))+
 geom_bar(stat="count")+
 ggtitle('Browser wise count')
d<-ggplot(online_data, aes(x=factor(OperatingSystems)))+
 geom_bar(stat="count")+
 ggtitle('OS wise count ')
library(cowplot)
plot_grid(a, b, c,d,labels = "AUTO", ncol = 2)
```

```{r}
relation <- lm(Revenue~ Administrative+Administrative_Duration+Informational+Informational_Duration+ProductRelated+ProductRelated_Duration+BounceRates+ExitRates+PageValues+SpecialDay+Month+OperatingSystems+Browser+Region+TrafficType+VisitorType+Weekend,data=online_data)
summary(relation)
```

```{r}
str(online_data)
```

